export const INDUSTRIES = [
  { value: 'ecommerce', label: 'E-commerce' },
  { value: 'real_estate', label: 'Real Estate' },
  { value: 'digital_marketing', label: 'Digital Marketing' },
  { value: 'social_media_management', label: 'Social Media Management' },
  { value: 'customer_service', label: 'Customer Service' },
  { value: 'bookkeeping', label: 'Bookkeeping' },
  { value: 'content_creation', label: 'Content Creation' },
  { value: 'graphic_design', label: 'Graphic Design' },
  { value: 'virtual_assistance', label: 'Virtual Assistance' },
  { value: 'data_entry', label: 'Data Entry' },
  { value: 'lead_generation', label: 'Lead Generation' },
  { value: 'email_marketing', label: 'Email Marketing' },
  { value: 'amazon_fba', label: 'Amazon FBA' },
  { value: 'shopify', label: 'Shopify' },
  { value: 'wordpress', label: 'WordPress' },
  { value: 'video_editing', label: 'Video Editing' },
  { value: 'podcast_management', label: 'Podcast Management' },
  { value: 'project_management', label: 'Project Management' },
  { value: 'human_resources', label: 'Human Resources' },
  { value: 'online_tutoring', label: 'Online Tutoring' },
  { value: 'travel_planning', label: 'Travel Planning' },
  { value: 'healthcare', label: 'Healthcare' },
  { value: 'finance', label: 'Finance' },
  { value: 'saas', label: 'SaaS' },
  { value: 'other', label: 'Other' }
];